Petstagram_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("Petstagram_project.common.urls")),
    path("accounts/", include("Petstagram_project.accounts.urls")),
    path("pets/", include("Petstagram_project.pets.urls")),
    path("photos/", include("Petstagram_project.photos.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Petstagram_project/common/models.py
from django.contrib.auth import get_user_model
from django.db import models

from Petstagram_project.photos.models import PhotoPet

UserModel = get_user_model()


class PhotoComment(models.Model):
    MAX_LENGTH_TEXT = 300

    text = models.CharField(
        max_length=MAX_LENGTH_TEXT,
        null=False,
        blank=False,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    modified_at = models.DateTimeField(
        auto_now=True,
    )

    photo_pet = models.ForeignKey(
        PhotoPet,
        on_delete=models.RESTRICT,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.RESTRICT,
    )


class PhotoLike(models.Model):

    photo_pet = models.ForeignKey(
        PhotoPet,
        on_delete=models.RESTRICT,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.RESTRICT,
    )

templates/partials/pets-card-item.html
{% load static %}

<div class="card">
    <div class="top">
        <div class="userDetails">
            <a href="{% url 'details profile' pk=1 %}">
                <div class="profilepic">
                    <div class="profile_img">
                        <div class="image">
                            <img src="{% static 'images/person.png' %}" alt="img8">
                        </div>
                    </div>
                </div>
            </a>

            <h3>
                <a href="{% url 'details profile' pk=1 %}">
                    Vesi
                </a>
                <br>
                <span>{{ photo.location }}</span>
            </h3>
        </div>
    </div>

    <div class="imgBx" id="photo-{{ photo.pk }}">
        <img src="{{ photo.photo.url }}" alt="post" class="cover">
    </div>

    <div class="bottom">
        <div class="actionBtns">
            <div class="left">
                <span class="heart">
                    <a href="{% url 'like pet photo' pk=photo.pk %}">
                        {% if photo.photolike_set.count > 0 %}
                            <i class="fa-solid fa-heart" style="color: #ed4040;"></i>
                        {% else %}
                            <i class="fa-regular fa-heart"></i>
                        {% endif %}
                    </a>
                </span>
                <a href="#">
                    <i class="fa-solid fa-share"></i>
                </a>
            </div>
        </div>

        <p class="likes">{{ photo.photolike_set.count }} likes</p>

        {% for tagged_pet in photo.pets.all %}
            <a href="{% url 'details pet' username="vesi" pet_slug=tagged_pet.slug %}">
                <p class="message">
                    <b>{{ tagged_pet.name }}</b>
                </p>
            </a>
        {% endfor %}

        <a href="{% url 'details photo' pk=photo.pk %}">
            <h4 class="details">See details</h4>
        </a>

        <h5 class="postTime">{{ photo.created_at|date:"d/M/Y" }}</h5>

        <div class="addComments">
            <form method="post" action="#">
                <label for="id_body">Body:</label>
                <textarea name="body" cols="40" rows="10" placeholder="Add comment..." maxlength="300"
                          required="" id="id_body">
                </textarea>
                <button type="submit">Post</button>
            </form>
        </div>

    </div>
</div>

templates/partials/pets-photos-list-card.html
{% load static %}

{% for photo in photo_list %}

    {% include "partials/pets-card-item.html" with photo=photo %}

{% empty %}

    <img class="no-posts" src="{% static 'images/no_posts.png' %}" alt="no posts image">

{% endfor %}

templates/partials/pets_photos_list_card.html
{% load static %}

{% for photo in photo_list %}

<div class="card">

    <div class="top">
        <div class="userDetails">
            <a href="{% url 'details profile' pk=1 %}">
                <div class="profilepic">
                    <div class="profile_img">
                        <div class="image">
                            <img src="{% static 'images/person.png' %}" alt="img8">
                        </div>
                    </div>
                </div>
            </a>

            <h3>
                <a href="{% url 'details profile' pk=1 %}">
                    Diyan Kalaydzhiev
                </a>
                <br>
                <span>{{ photo.location }}</span>
            </h3>
        </div>
    </div>

    <div class="imgBx" id="photo-{{ photo.pk }} %}">
        <img src="{{ photo.photo.url }}" alt="post" class="cover">
    </div>

    <div class="bottom">
        <div class="actionBtns">
            <div class="left">
                <span class="heart">
                    <a href="#">
                        <i class="fa-solid fa-heart" style="color: #ed4040;"></i>
                        <i class="fa-regular fa-heart"></i>
                    </a>
                </span>

                <a href="#">
                    <i class="fa-solid fa-share"></i>
                </a>

            </div>
        </div>

        <p class="likes">203 likes</p>

        {% for tagged_pet in photo.pets.all %}
            <a href="{% url 'details pet' username="vesi" pet_slug=tagged_pet.slug %}">
                <p class="message">
                    <b>{{ tagged_pet.name }}</b>
                </p>
            </a>
        {% endfor %}

        <a href="{% url 'details photo' pk=photo.pk %}">
            <h4 class="details">See details</h4>
        </a>

        <h5 class="postTime">{{ photo.created_at|date:"d/M/Y" }}</h5>

        <div class="addComments">

            <form method="post" action="#">
                <label for="id_body">Body:</label>
                <textarea name="body" cols="40" rows="10" placeholder="Add comment..." maxlength="300"
                          required="" id="id_body"></textarea>
                <button type="submit">Post</button>
            </form>

        </div>

    </div>
</div>

{% endfor %}

<img class="no-posts" src="{% static 'images/no_posts.png' %}" alt="no posts image">